"""resolve_core — shared module for Resolve Lambdas."""

from resolve_core.dispatch import (
    evaluate_dispatch,
    load_dispatch_config,
    validate_dispatch_pattern,
    validate_event_categories,
    validate_rule_id,
)
from resolve_core.campaign import (
    CampaignResult,
    CompletionResult,
    VALID_CAMPAIGN_STATUSES,
    create_or_update_campaign,
    derive_campaign_id,
    determine_campaign_type,
    recalculate_completion,
    update_campaign_status,
)
from resolve_core.event_parser import (
    ActionabilityResult,
    PageInfo,
    coerce_page_fields,
    extract_account_tags,
    extract_description,
    extract_entities,
    extract_resource_tags,
    generate_resource_arn,
    infer_actionability,
    parse_health_date,
    should_filter_backup_event,
)
from resolve_core.pagination import (
    PaginationPath,
    ResourceCounts,
    count_resources,
    determine_pagination_path,
    should_publish_sns,
)
from resolve_core.resources import (
    WriteResult,
    update_resource_status,
    write_resources,
)
from resolve_core.routing import (
    extract_affected_account,
    extract_tag_value,
    resolve_account_routing,
    resolve_routing,
)
from resolve_core.tags import (
    normalize_tags,
    sanitize_for_label,
    extract_region_from_arn,
    fetch_resource_tags,
)
from resolve_core.payload import (
    publish_or_offload,
    resolve_payload,
)
from resolve_core.config_schema import (
    PK_ITSM_PLATFORM,
    PK_JIRA_CONNECTION,
    PK_SNOW_CONNECTION,
    PK_ROUTING_DEFAULT,
    PK_ROUTING_PREFIX,
    PK_DISPATCH_PRESET,
    PK_DISPATCH_RULE_PREFIX,
    PK_TELEMETRY,
    DEFAULT_PLATFORM,
    resolve_platforms,
    operative_platform,
)
from resolve_core.constants import (
    COMPASS_LABEL,
    ORPHAN_LABEL,
    ORPHAN_STATUS_KEY,
    ORPHAN_COUNT_FIELD,
    ORPHAN_ALERT_THRESHOLD,
)

__all__ = [
    "evaluate_dispatch",
    "load_dispatch_config",
    "validate_dispatch_pattern",
    "validate_event_categories",
    "validate_rule_id",
    "parse_health_date",
    "extract_entities",
    "generate_resource_arn",
    "extract_description",
    "coerce_page_fields",
    "infer_actionability",
    "extract_account_tags",
    "extract_resource_tags",
    "should_filter_backup_event",
    "normalize_tags",
    "sanitize_for_label",
    "extract_region_from_arn",
    "fetch_resource_tags",
    "determine_pagination_path",
    "should_publish_sns",
    "count_resources",
    "derive_campaign_id",
    "determine_campaign_type",
    "create_or_update_campaign",
    "recalculate_completion",
    "update_campaign_status",
    "write_resources",
    "update_resource_status",
    "ActionabilityResult",
    "PageInfo",
    "PaginationPath",
    "ResourceCounts",
    "CampaignResult",
    "CompletionResult",
    "VALID_CAMPAIGN_STATUSES",
    "WriteResult",
    "extract_affected_account",
    "extract_tag_value",
    "resolve_account_routing",
    "resolve_routing",
    "publish_or_offload",
    "resolve_payload",
    "PK_ITSM_PLATFORM",
    "PK_JIRA_CONNECTION",
    "PK_SNOW_CONNECTION",
    "PK_ROUTING_DEFAULT",
    "PK_ROUTING_PREFIX",
    "PK_DISPATCH_PRESET",
    "PK_DISPATCH_RULE_PREFIX",
    "PK_TELEMETRY",
    "DEFAULT_PLATFORM",
    "resolve_platforms",
    "operative_platform",
    "COMPASS_LABEL",
    "ORPHAN_LABEL",
    "ORPHAN_STATUS_KEY",
    "ORPHAN_COUNT_FIELD",
    "ORPHAN_ALERT_THRESHOLD",
]
